"""Thruster allocation model for the Team Tiburon 8-thruster AUV.

The 6x8 matrix A below is the single source of truth. Everything else
(B+, the C header, the analysis) is derived from it.

    tau = A @ T        tau = [Fx Fy Fz Mx My Mz],  T = [T1 .. T8]

T1-T4 are the vertical thrusters, T5-T8 the horizontal thrusters at 45 deg.
Thrust is normalised: |T_i| <= 1 is full ESC authority.

Run as a script to regenerate include/alloc_matrix.h:

    python python/model.py            # write the header, print properties
    python python/model.py --check    # exit 1 if the header is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "include" / "alloc_matrix.h"

DOF = ("surge", "sway", "heave", "roll", "pitch", "yaw")
WRENCH = ("Fx", "Fy", "Fz", "Mx", "My", "Mz")
N_DOF, N_THR = 6, 8

# Rows Fx Fy Fz Mx My Mz; columns T1..T8. Same values as pseudoinverse.m and
# B_forward in the vehicle firmware.
A = np.array([
    [0.0,     0.0,     0.0,     0.0,     0.7070, -0.7070,  0.7070,  0.7070],
    [0.0,     0.0,     0.0,     0.0,    -0.7070,  0.7070,  0.7070, -0.7070],
    [1.0,     1.0,     1.0,     1.0,     0.0,     0.0,     0.0,     0.0   ],
    [0.1700, -0.1200,  0.1200, -0.1200, -0.0140,  0.0140, -0.0140,  0.0140],
    [-0.1200, -0.1200, 0.1500,  0.1500, -0.0140, -0.0140, -0.0140, -0.0140],
    [0.0,     0.0,     0.0,     0.0,     0.0346,  0.0346, -0.3250,  0.3250],
])

# The firmware stores B+ as 4-decimal literals. The generated header keeps
# that quantisation so the C code runs the same constants that flew.
FIRMWARE_DECIMALS = 4

# Thrusters each DOF group drives in the firmware (computeAllocation()).
VERT_THR = (0, 1, 2, 3)          # heave, roll, pitch
HORIZ_THR = (4, 5, 6, 7)         # surge, sway (translation) and yaw
VERT_DOF = (2, 3, 4)
TRANS_DOF = (0, 1)
YAW_DOF = (5,)


def pinv() -> np.ndarray:
    """Full-precision Moore-Penrose pseudo-inverse of A (8x6)."""
    return np.linalg.pinv(A)


def firmware_pinv() -> np.ndarray:
    """B+ rounded to the firmware's 4 decimals, with -0.0 normalised to 0.0."""
    p = np.round(pinv(), FIRMWARE_DECIMALS)
    p[p == 0.0] = 0.0
    return p


def full_pinv_f32() -> np.ndarray:
    """Full-precision B+ as float32, used by the v2 allocators (not flown).
    SVD round-off below 1e-9 (T7's 1e-16 entries) is set to exactly 0."""
    p = pinv()
    p[np.abs(p) < 1e-9] = 0.0
    return p.astype(np.float32)


def block_pinv(p: np.ndarray | None = None) -> np.ndarray:
    """The part of B+ the firmware actually uses.

    T1-T4 only see heave/roll/pitch; T5-T8 only see surge/sway/yaw. Every
    other entry of B+ is never read by computeAllocation().
    """
    p = firmware_pinv() if p is None else p
    m = np.zeros_like(p)
    for i in VERT_THR:
        for k in VERT_DOF:
            m[i, k] = p[i, k]
    for i in HORIZ_THR:
        for k in TRANS_DOF + YAW_DOF:
            m[i, k] = p[i, k]
    return m


def properties() -> dict:
    s = np.linalg.svd(A, compute_uv=False)
    return {
        "rank": int(np.linalg.matrix_rank(A)),
        "singular_values": s.tolist(),
        "condition_number": float(s[0] / s[-1]),
        "column_norms": np.linalg.norm(A, axis=0).tolist(),
    }


def _fmt(v: float) -> str:
    return f"{v:.{FIRMWARE_DECIMALS}f}"


def _fmt32(v: float) -> str:
    """Shortest text that round-trips a float32, always a valid C literal."""
    t = f"{float(v):.9g}"
    return t if any(c in t for c in ".e") else t + ".0"


def source_hash() -> str:
    """SHA-256 of A as printed to 4 decimals, row-major."""
    text = "\n".join(",".join(_fmt(v) for v in row) for row in A)
    return hashlib.sha256(text.encode()).hexdigest()


def render_header() -> str:
    p = firmware_pinv()
    props = properties()

    def rows(m: np.ndarray, names) -> str:
        out = []
        for r, name in zip(m, names):
            vals = ", ".join(f"{_fmt(v):>7}f" for v in r)
            out.append(f"    {{ {vals} }},   /* {name} */")
        return "\n".join(out)

    def rows32(m: np.ndarray, names) -> str:
        out = []
        for r, name in zip(m, names):
            vals = ", ".join(f"{_fmt32(v):>15}f" for v in r)
            out.append(f"    {{ {vals} }},   /* {name} */")
        return "\n".join(out)

    return f"""\
/*
 * alloc_matrix.h - GENERATED by python/model.py. DO NOT EDIT.
 *
 * Source matrix A sha256: {source_hash()}
 * rank {props['rank']}, condition number {props['condition_number']:.4f}
 *
 * B+ = pinv(A), rounded to {FIRMWARE_DECIMALS} decimals exactly as stored in the vehicle
 * firmware. Regenerate with: python python/model.py
 */
#ifndef ALLOC_MATRIX_H
#define ALLOC_MATRIX_H

#define ALLOC_MATRIX_SHA256 "{source_hash()}"

/* Forward matrix A (6x8): tau = A * T. Rows Fx Fy Fz Mx My Mz. Not used at runtime. */
static const float ALLOC_A[6][8] = {{
{rows(A, WRENCH)}
}};

/* Pseudo-inverse B+ (8x6): T = B+ * U. Columns surge sway heave roll pitch yaw. */
static const float ALLOC_B_PINV[8][6] = {{
{rows(p, [f"T{i + 1}" for i in range(N_THR)])}
}};

/* Full-precision B+ (float32, 9 significant digits round-trip exactly).
 * Used only by alloc_v2.c, which has NOT flown. */
static const float ALLOC_B_PINV_FULL[8][6] = {{
{rows32(full_pinv_f32(), [f"T{i + 1}" for i in range(N_THR)])}
}};

#endif /* ALLOC_MATRIX_H */
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if include/alloc_matrix.h is out of date")
    args = ap.parse_args()

    text = render_header()
    if args.check:
        if not HEADER.exists() or HEADER.read_text() != text:
            print(f"{HEADER.relative_to(ROOT)} is stale: run python python/model.py")
            return 1
        print(f"{HEADER.relative_to(ROOT)} is up to date")
        return 0

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(text, newline="\n")
    print(f"wrote {HEADER.relative_to(ROOT)}")
    print(json.dumps(properties(), indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
