/*
 * alloc_matrix.h - GENERATED by python/model.py. DO NOT EDIT.
 *
 * Source matrix A sha256: 89f687f0ad327ab2c837ee00b14f3f6d9dde9405c4e9a494a11883a89b0a5c08
 * rank 6, condition number 8.0470
 *
 * B+ = pinv(A), rounded to 4 decimals exactly as stored in the vehicle
 * firmware. Regenerate with: python python/model.py
 */
#ifndef ALLOC_MATRIX_H
#define ALLOC_MATRIX_H

#define ALLOC_MATRIX_SHA256 "89f687f0ad327ab2c837ee00b14f3f6d9dde9405c4e9a494a11883a89b0a5c08"

/* Forward matrix A (6x8): tau = A * T. Rows Fx Fy Fz Mx My Mz. Not used at runtime. */
static const float ALLOC_A[6][8] = {
    {  0.0000f,  0.0000f,  0.0000f,  0.0000f,  0.7070f, -0.7070f,  0.7070f,  0.7070f },   /* Fx */
    {  0.0000f,  0.0000f,  0.0000f,  0.0000f, -0.7070f,  0.7070f,  0.7070f, -0.7070f },   /* Fy */
    {  1.0000f,  1.0000f,  1.0000f,  1.0000f,  0.0000f,  0.0000f,  0.0000f,  0.0000f },   /* Fz */
    {  0.1700f, -0.1200f,  0.1200f, -0.1200f, -0.0140f,  0.0140f, -0.0140f,  0.0140f },   /* Mx */
    { -0.1200f, -0.1200f,  0.1500f,  0.1500f, -0.0140f, -0.0140f, -0.0140f, -0.0140f },   /* My */
    {  0.0000f,  0.0000f,  0.0000f,  0.0000f,  0.0346f,  0.0346f, -0.3250f,  0.3250f },   /* Mz */
};

/* Pseudo-inverse B+ (8x6): T = B+ * U. Columns surge sway heave roll pitch yaw. */
static const float ALLOC_B_PINV[8][6] = {
    { -0.0349f, -0.0776f,  0.2493f,  2.0482f, -1.6573f, -0.2618f },   /* T1 */
    { -0.0448f, -0.0089f,  0.3060f, -2.0430f, -2.0306f,  0.0586f },   /* T2 */
    {  0.0439f,  0.0148f,  0.1989f,  1.6903f,  1.9984f, -0.0310f },   /* T3 */
    {  0.0358f,  0.0717f,  0.2459f, -1.6955f,  1.6895f,  0.2341f },   /* T4 */
    {  0.0765f, -0.5493f,  0.0036f, -0.0622f, -0.1885f, -1.0178f },   /* T5 */
    {  0.0617f,  0.8347f,  0.0029f, -0.0503f, -0.1523f,  1.9589f },   /* T6 */
    {  0.7072f,  0.7072f,  0.0000f,  0.0000f,  0.0000f,  0.0000f },   /* T7 */
    {  0.6925f,  0.6768f, -0.0007f,  0.0120f,  0.0363f,  2.9767f },   /* T8 */
};

#endif /* ALLOC_MATRIX_H */
